server:
  port: 9001

spring:
  application:
    name: eureka01

eureka:
  server:
    # https://blog.csdn.net/qq_26975307/article/details/86563590
    # https://www.cnblogs.com/breath-taking/articles/7940364.html
    enableSelfPreservation: false

  instance:
    hostname: eureka01      # eureka 实例名称

    ## 单一节点（方案一）
  client:
    # 表示是否从eureka server获取注册信息，如果是单一节点，不需要同步其他eureka server节点，则可以设置为false，但此处为集群，应该设置为true，默认为true，可不设置。
    # 在做注册中心集群的时候，register-with-eureka必须打开，因为需要进行相互注册，不然副本无法可用。
    register-with-eureka: false # 单一节点不向注册中心注册自己
    fetch-registry: false       # 是否检索服务
    service-url:
      defaultZone: http://eureka01:9001/eureka/ # 注册中心访问地址，单一节点不向注册中心注册自己


      ## 多个节点（方案二）
      #        client:
      # 表示是否从eureka server获取注册信息，如果是单一节点，不需要同步其他eureka server节点，则可以设置为false，但此处为集群，应该设置为true，默认为true，可不设置。
      # 在做注册中心集群的时候，register-with-eureka必须打开，因为需要进行相互注册，不然副本无法可用。
      #    register-with-eureka: true # 集群相互注册
      #    fetch-registry: true       # 是否检索服务
      #        service-url:
      #    defaultZone: http://eureka:9000/eureka/,http://eureka02:9002/eureka/  # 注册中心访问地址，集群相互注册