server:
  port: 3004

spring:
  application:
    name: feign-test-order

eureka:
  instance:
    instance-id: order-api-3004
    prefer-ip-address: true # 访问路径可以显示 IP
  client:
    service-url:
      defaultZone: http://eureka3000:3000/eureka/  # 注册中心访问地址