server:
    port: 8100

spring:
  application:
    name: ORDER
    
eureka:
    instance:
        instance-id: order-api-8100
        prefer-ip-address: true # 访问路径可以显示 IP
    client:
        service-url:
            defaultZone: http://localhost:9000/eureka/  # 注册中心访问地址

# 开启服务降级功能
feign:
  hystrix:
    enabled: true

# 开放hystrix监控端口
managemeng:
  endpoints:
    web:
      exposure:
        include: "*"
