server:
  port: 2005

spring:
  application:
    name: ribbon-test-order

eureka:
  instance:
    instance-id: order-api-2005
    prefer-ip-address: true # 访问路径可以显示 IP
  client:
    service-url:
      defaultZone: http://eureka2001:2001/eureka/  # 注册中心访问地址