server:
  port: 2004

spring:
  application:
    name: ribbon-test-goods

eureka:
  instance:
    instance-id: goods-api-2004
    prefer-ip-address: true # 访问路径可以显示 IP
  client:
    service-url:
      defaultZone: http://eureka2001:2001/eureka/  # 注册中心访问地址