server:
  port: 9600

spring:
  application:
    name: gateway

eureka:
  instance:
    instance-id: gateway-9600
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:9000/eureka/  # 注册中心访问地址
zuul:
#  prefix: /api      # 路由加前缀
  sensitive-headers: # 设置全局敏感头，如果为空，表示接收所有敏感头信息
  routes:
    extlight:   # 任意名字，保证唯一即可
      path: /extlight/**  # 自定义，真正用到的请求地址
      service-id: ORDER   # 路由到的目标服务名称
  ignored-patterns:
    - /order/order/**     # 禁用路由

