server:
  port: 3002

spring:
  application:
    name: feign-test-goods

eureka:
  instance:
    instance-id: goods-api-3002
    prefer-ip-address: true # 访问路径可以显示 IP
  client:
    service-url:
      defaultZone: http://eureka3000:3000/eureka/ # 注册中心访问地址